Parameters:

    AvailabilityZone:
        Description: The AZ in which the RDS instance is deployed
        Type: String
        Default: us-west-2a

    SecurityGroup:
        Description: Select the Security Group to use for this RDS instance
        Type: AWS::EC2::SecurityGroup::Id

    SubnetGroupName:
        Description: The Subnet Group(s) to which this RDS instance should be deployed
        Type: String

    ## Instance-specific parameters

    InstanceName:
        Description: The name by which the DB instance is labelled in the RDS console
        Type: String

    InstanceSize:
        Description: The instance class (size) for this RDS instance
        Type: String
        Default: db.t2.micro

    InstanceStorage:
        Description: The amount of storage in GB allocated to the RDS instance
        Type: String
        ConstraintDescription: must be between 5 and 1024 GB.

    MasterUsername:
        Description: The database admin account username
        Type: String
        ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
        Default: dummyusername1

    MasterPassword:
        Description: The database admin account password
        Type: String
        ConstraintDescription: must contain only alphanumeric characters.
        Default: dummypassword2

    ## Database-specific parameters

    DatabaseName:
        Description: The name of the primary database on this instance
        Type: String

Resources:

    PostgresRDS:
        Type: AWS::RDS::DBInstance
        Properties:
            AllowMajorVersionUpgrade: False
            AutoMinorVersionUpgrade: True
            AllocatedStorage: !Ref InstanceStorage
            StorageType: gp2
            AvailabilityZone: !Ref AvailabilityZone
            DBInstanceClass: !Ref InstanceSize
            DBInstanceIdentifier: !Ref InstanceName
            DBName: !Ref DatabaseName
            DBSubnetGroupName: !Ref SubnetGroupName
            Engine: postgres
            MasterUsername: !Ref MasterUsername
            MasterUserPassword: !Ref MasterPassword
            MultiAZ: false
            Port: 5432
            PubliclyAccessible: true
            Tags:
                - Key: Name
                  Value: !Ref InstanceName
            VPCSecurityGroups:
                - !Ref SecurityGroup
